INSERT INTO DNDBookTable (BookName)
VALUES
('Player''s Handbook'),
('Player''s Handbook (2nd Edition)'),
('Player''s Handbook (2nd Edition, Revised)'),

('Player''s Option: Combat & Tactics'),
('Player''s Option: Skills & Powers'),
('Player''s Option: Spells & Magic'),


('Greyhawk Adventures (1st Edition AD&D)'),
('The City of Greyhawk Boxed Set'),
('Treasures of Greyhawk'),
('Forgotten Realms Adventures'),
('The Astromundi Cluster Boxed Set'),
('Al-Qadim Arabian Adventures'),

('Cult of the Dragon'),
('Defilers and Preservers: Wizards of Athas'),
('Dragonlance Adventures (1st Edition AD&D)'),
('Dark Sun Boxed Set'),
('Dragon Kings'),
('Elves of Evermeet'),
('Halls of the High King'),
('The Drow of the Underdark'),
('The Code of the Harpers'),
('Haunted Halls of Eveningstar'),
('The Magister'),
('Dreams of the Red Wizards'),
('The Shining South'),
('Hellbound: The Blood War Boxed Set'),
('Legends & Lore'),
('Monstrous Compendium Volume Three - Forgotten Realms'),
('Monstrous Compendium Volume Fourteen - Fiend Folio'),
('Menzoberranzan Boxed Set'),
('Oriental Adventures (1st Edition AD&D)'),
('Pages from the Mages'),
('The Planewalker''s Handbook'),

('Powers and Pantheons'),
('Planescape Boxed Set'),
('Ravenloft Campaign Setting Boxed Set'),
('The Ruins of Myth Drannor Boxed Set'),
('Ravenloft Realm of Terror Boxed Set'),
('The Ruins of Undermountain Boxed Set'),
('The Ruins of Undermountain II: The Deep Levels Boxed Set'),
('Ruins of Zhentil Keep Boxed Set'),
('Van Richten''s Guide to the Lich'),
('Spellbound Boxed Set'),
('Spelljammer Boxed Set'),
('Wildspace'),
('Lost Ships'),
('The Seven Sisters'),
('Tome of Magic'),
('Flames of the Falcon'),

('The Complete Fighter''s Handbook'),
('The Complete Thief''s Handbook'),
('The Complete Priest''s Handbook'),
('The Complete Wizard''s Handbook'),
('The Complete Psionics Handbook'),
('The Complete Book of Dwarves'),
('The Complete Bard''s Handbook'),
('The Complete Book of Elves'),
('The Complete Book of Gnomes & Halflings'),
('The Complete Book of Humanoids'),
('The Complete Ranger''s Handbook'),
('The Complete Paladin''s Handbook'),
('The Complete Druid''s Handbook'),
('The Complete Barbarian''s Handbook'),
('The Complete Ninja''s Handbook'),

('The Complete Book of Necromancers'),

('The Complete Sha''ir''s Handbook'),

('Wizard''s Spell Compendium Volume One'),
('Wizard''s Spell Compendium Volume Two'),
('Wizard''s Spell Compendium Volume Three'),
('Wizard''s Spell Compendium Volume Four'),

('Priest''s Spell Compendium Volume One'),
('Priest''s Spell Compendium Volume Two'),
('Priest''s Spell Compendium Volume Three'),

('Dragon Magazine Issue 001'),
('Dragon Magazine Issue 002'),
('Dragon Magazine Issue 003'),
('Dragon Magazine Issue 004'),
('Dragon Magazine Issue 005'),
('Dragon Magazine Issue 006'),
('Dragon Magazine Issue 007'),
('Dragon Magazine Issue 008'),
('Dragon Magazine Issue 009'),
('Dragon Magazine Issue 010'),
('Dragon Magazine Issue 011'),
('Dragon Magazine Issue 012'),
('Dragon Magazine Issue 013'),
('Dragon Magazine Issue 014'),
('Dragon Magazine Issue 015'),
('Dragon Magazine Issue 016'),
('Dragon Magazine Issue 017'),
('Dragon Magazine Issue 018'),
('Dragon Magazine Issue 019'),
('Dragon Magazine Issue 020'),
('Dragon Magazine Issue 021'),
('Dragon Magazine Issue 022'),
('Dragon Magazine Issue 023'),
('Dragon Magazine Issue 024'),
('Dragon Magazine Issue 025'),
('Dragon Magazine Issue 026'),
('Dragon Magazine Issue 027'),
('Dragon Magazine Issue 028'),
('Dragon Magazine Issue 029'),
('Dragon Magazine Issue 030'),
('Dragon Magazine Issue 031'),
('Dragon Magazine Issue 032'),
('Dragon Magazine Issue 033'),
('Dragon Magazine Issue 034'),
('Dragon Magazine Issue 035'),
('Dragon Magazine Issue 036'),
('Dragon Magazine Issue 037'),
('Dragon Magazine Issue 038'),
('Dragon Magazine Issue 039'),
('Dragon Magazine Issue 040'),
('Dragon Magazine Issue 041'),
('Dragon Magazine Issue 042'),
('Dragon Magazine Issue 043'),
('Dragon Magazine Issue 044'),
('Dragon Magazine Issue 045'),
('Dragon Magazine Issue 046'),
('Dragon Magazine Issue 047'),
('Dragon Magazine Issue 048'),
('Dragon Magazine Issue 049'),
('Dragon Magazine Issue 050'),
('Dragon Magazine Issue 051'),
('Dragon Magazine Issue 052'),
('Dragon Magazine Issue 053'),
('Dragon Magazine Issue 054'),
('Dragon Magazine Issue 055'),
('Dragon Magazine Issue 056'),
('Dragon Magazine Issue 057'),
('Dragon Magazine Issue 058'),
('Dragon Magazine Issue 059'),
('Dragon Magazine Issue 060'),
('Dragon Magazine Issue 061'),
('Dragon Magazine Issue 062'),
('Dragon Magazine Issue 063'),
('Dragon Magazine Issue 064'),
('Dragon Magazine Issue 065'),
('Dragon Magazine Issue 066'),
('Dragon Magazine Issue 067'),
('Dragon Magazine Issue 068'),
('Dragon Magazine Issue 069'),
('Dragon Magazine Issue 070'),
('Dragon Magazine Issue 071'),
('Dragon Magazine Issue 072'),
('Dragon Magazine Issue 073'),
('Dragon Magazine Issue 074'),
('Dragon Magazine Issue 075'),
('Dragon Magazine Issue 076'),
('Dragon Magazine Issue 077'),
('Dragon Magazine Issue 078'),
('Dragon Magazine Issue 079'),
('Dragon Magazine Issue 080'),
('Dragon Magazine Issue 081'),
('Dragon Magazine Issue 082'),
('Dragon Magazine Issue 083'),
('Dragon Magazine Issue 084'),
('Dragon Magazine Issue 085'),
('Dragon Magazine Issue 086'),
('Dragon Magazine Issue 087'),
('Dragon Magazine Issue 088'),
('Dragon Magazine Issue 089'),
('Dragon Magazine Issue 090'),
('Dragon Magazine Issue 091'),
('Dragon Magazine Issue 092'),
('Dragon Magazine Issue 093'),
('Dragon Magazine Issue 094'),
('Dragon Magazine Issue 095'),
('Dragon Magazine Issue 096'),
('Dragon Magazine Issue 097'),
('Dragon Magazine Issue 098'),
('Dragon Magazine Issue 099'),
('Dragon Magazine Issue 100'),
('Dragon Magazine Issue 101'),
('Dragon Magazine Issue 102'),
('Dragon Magazine Issue 103'),
('Dragon Magazine Issue 104'),
('Dragon Magazine Issue 105'),
('Dragon Magazine Issue 106'),
('Dragon Magazine Issue 107'),
('Dragon Magazine Issue 108'),
('Dragon Magazine Issue 109'),
('Dragon Magazine Issue 110'),
('Dragon Magazine Issue 111'),
('Dragon Magazine Issue 112'),
('Dragon Magazine Issue 113'),
('Dragon Magazine Issue 114'),
('Dragon Magazine Issue 115'),
('Dragon Magazine Issue 116'),
('Dragon Magazine Issue 117'),
('Dragon Magazine Issue 118'),
('Dragon Magazine Issue 119'),
('Dragon Magazine Issue 120'),
('Dragon Magazine Issue 121'),
('Dragon Magazine Issue 122'),
('Dragon Magazine Issue 123'),
('Dragon Magazine Issue 124'),
('Dragon Magazine Issue 125'),
('Dragon Magazine Issue 126'),
('Dragon Magazine Issue 127'),
('Dragon Magazine Issue 128'),
('Dragon Magazine Issue 129'),
('Dragon Magazine Issue 130'),
('Dragon Magazine Issue 131'),
('Dragon Magazine Issue 132'),
('Dragon Magazine Issue 133'),
('Dragon Magazine Issue 134'),
('Dragon Magazine Issue 135'),
('Dragon Magazine Issue 136'),
('Dragon Magazine Issue 137'),
('Dragon Magazine Issue 138'),
('Dragon Magazine Issue 139'),
('Dragon Magazine Issue 140'),
('Dragon Magazine Issue 141'),
('Dragon Magazine Issue 142'),
('Dragon Magazine Issue 143'),
('Dragon Magazine Issue 144'),
('Dragon Magazine Issue 145'),
('Dragon Magazine Issue 146'),
('Dragon Magazine Issue 147'),
('Dragon Magazine Issue 148'),
('Dragon Magazine Issue 149'),
('Dragon Magazine Issue 150'),
('Dragon Magazine Issue 151'),
('Dragon Magazine Issue 152'),
('Dragon Magazine Issue 153'),
('Dragon Magazine Issue 154'),
('Dragon Magazine Issue 155'),
('Dragon Magazine Issue 156'),
('Dragon Magazine Issue 157'),
('Dragon Magazine Issue 158'),
('Dragon Magazine Issue 159'),
('Dragon Magazine Issue 160'),
('Dragon Magazine Issue 161'),
('Dragon Magazine Issue 162'),
('Dragon Magazine Issue 163'),
('Dragon Magazine Issue 164'),
('Dragon Magazine Issue 165'),
('Dragon Magazine Issue 166'),
('Dragon Magazine Issue 167'),
('Dragon Magazine Issue 168'),
('Dragon Magazine Issue 169'),
('Dragon Magazine Issue 170'),
('Dragon Magazine Issue 171'),
('Dragon Magazine Issue 172'),
('Dragon Magazine Issue 173'),
('Dragon Magazine Issue 174'),
('Dragon Magazine Issue 175'),
('Dragon Magazine Issue 176'),
('Dragon Magazine Issue 177'),
('Dragon Magazine Issue 178'),
('Dragon Magazine Issue 179'),
('Dragon Magazine Issue 180'),
('Dragon Magazine Issue 181'),
('Dragon Magazine Issue 182'),
('Dragon Magazine Issue 183'),
('Dragon Magazine Issue 184'),
('Dragon Magazine Issue 185'),
('Dragon Magazine Issue 186'),
('Dragon Magazine Issue 187'),
('Dragon Magazine Issue 188'),
('Dragon Magazine Issue 189'),
('Dragon Magazine Issue 190'),
('Dragon Magazine Issue 191'),
('Dragon Magazine Issue 192'),
('Dragon Magazine Issue 193'),
('Dragon Magazine Issue 194'),
('Dragon Magazine Issue 195'),
('Dragon Magazine Issue 196'),
('Dragon Magazine Issue 197'),
('Dragon Magazine Issue 198'),
('Dragon Magazine Issue 199'),
('Dragon Magazine Issue 200'),
('Dragon Magazine Issue 201'),
('Dragon Magazine Issue 202'),
('Dragon Magazine Issue 203'),
('Dragon Magazine Issue 204'),
('Dragon Magazine Issue 205'),
('Dragon Magazine Issue 206'),
('Dragon Magazine Issue 207'),
('Dragon Magazine Issue 208'),
('Dragon Magazine Issue 209'),
('Dragon Magazine Issue 210'),
('Dragon Magazine Issue 211'),
('Dragon Magazine Issue 212'),
('Dragon Magazine Issue 213'),
('Dragon Magazine Issue 214'),
('Dragon Magazine Issue 215'),
('Dragon Magazine Issue 216'),
('Dragon Magazine Issue 217'),
('Dragon Magazine Issue 218'),
('Dragon Magazine Issue 219'),
('Dragon Magazine Issue 220'),
('Dragon Magazine Issue 221'),
('Dragon Magazine Issue 222'),
('Dragon Magazine Issue 223'),
('Dragon Magazine Issue 224'),
('Dragon Magazine Issue 225'),
('Dragon Magazine Issue 226'),
('Dragon Magazine Issue 227'),
('Dragon Magazine Issue 228'),
('Dragon Magazine Issue 229'),
('Dragon Magazine Issue 230'),
('Dragon Magazine Issue 231'),
('Dragon Magazine Issue 232'),
('Dragon Magazine Issue 233'),
('Dragon Magazine Issue 234'),
('Dragon Magazine Issue 235'),
('Dragon Magazine Issue 236'),
('Dragon Magazine Issue 237'),
('Dragon Magazine Issue 238'),
('Dragon Magazine Issue 239'),
('Dragon Magazine Issue 240'),
('Dragon Magazine Issue 241'),
('Dragon Magazine Issue 242'),
('Dragon Magazine Issue 243'),
('Dragon Magazine Issue 244'),
('Dragon Magazine Issue 245'),
('Dragon Magazine Issue 246'),
('Dragon Magazine Issue 247'),
('Dragon Magazine Issue 248'),
('Dragon Magazine Issue 249'),
('Dragon Magazine Issue 250'),
('Dragon Magazine Issue 251'),
('Dragon Magazine Issue 252'),
('Dragon Magazine Issue 253'),
('Dragon Magazine Issue 254'),
('Dragon Magazine Issue 255'),
('Dragon Magazine Issue 256'),
('Dragon Magazine Issue 257'),
('Dragon Magazine Issue 258'),
('Dragon Magazine Issue 259'),
('Dragon Magazine Issue 260'),
('Dragon Magazine Issue 261'),
('Dragon Magazine Issue 262'),
('Dragon Magazine Issue 263'),
('Dragon Magazine Issue 264'),
('Dragon Magazine Issue 265'),
('Dragon Magazine Issue 266'),
('Dragon Magazine Issue 267'),
('Dragon Magazine Issue 268'),
('Dragon Magazine Issue 269'),
('Dragon Magazine Issue 270'),
('Dragon Magazine Issue 271'),
('Dragon Magazine Issue 272'),
('Dragon Magazine Issue 273'),
('Dragon Magazine Issue 274'),
('Dragon Magazine Issue 275'),
('Dragon Magazine Issue 276'),
('Dragon Magazine Issue 277'),
('Dragon Magazine Issue 278'),
('Dragon Magazine Issue 279'),
('Dragon Magazine Issue 280'),
('Dragon Magazine Issue 281'),
('Dragon Magazine Issue 282'),
('Dragon Magazine Issue 283'),
('Dragon Magazine Issue 284'),
('Dragon Magazine Issue 285'),
('Dragon Magazine Issue 286'),
('Dragon Magazine Issue 287'),
('Dragon Magazine Issue 288'),
('Dragon Magazine Issue 289'),
('Dragon Magazine Issue 290'),
('Dragon Magazine Issue 291'),
('Dragon Magazine Issue 292'),
('Dragon Magazine Issue 293'),
('Dragon Magazine Issue 294'),
('Dragon Magazine Issue 295'),
('Dragon Magazine Issue 296'),
('Dragon Magazine Issue 297'),
('Dragon Magazine Issue 298'),
('Dragon Magazine Issue 299'),
('Dragon Magazine Issue 300'),
('Dragon Magazine Issue 301'),
('Dragon Magazine Issue 302'),
('Dragon Magazine Issue 303'),
('Dragon Magazine Issue 304'),
('Dragon Magazine Issue 305'),
('Dragon Magazine Issue 306'),
('Dragon Magazine Issue 307'),
('Dragon Magazine Issue 308'),
('Dragon Magazine Issue 309'),
('Dragon Magazine Issue 310'),
('Dragon Magazine Issue 311'),
('Dragon Magazine Issue 312'),
('Dragon Magazine Issue 313'),
('Dragon Magazine Issue 314'),
('Dragon Magazine Issue 315'),
('Dragon Magazine Issue 316'),
('Dragon Magazine Issue 317'),
('Dragon Magazine Issue 318'),
('Dragon Magazine Issue 319'),
('Dragon Magazine Issue 320'),
('Dragon Magazine Issue 321'),
('Dragon Magazine Issue 322'),
('Dragon Magazine Issue 323'),
('Dragon Magazine Issue 324'),
('Dragon Magazine Issue 325'),
('Dragon Magazine Issue 326'),
('Dragon Magazine Issue 327'),
('Dragon Magazine Issue 328'),
('Dragon Magazine Issue 329'),
('Dragon Magazine Issue 330'),
('Dragon Magazine Issue 331'),
('Dragon Magazine Issue 332'),
('Dragon Magazine Issue 333'),
('Dragon Magazine Issue 334'),
('Dragon Magazine Issue 335'),
('Dragon Magazine Issue 336'),
('Dragon Magazine Issue 337'),
('Dragon Magazine Issue 338'),
('Dragon Magazine Issue 339'),
('Dragon Magazine Issue 340'),
('Dragon Magazine Issue 341'),
('Dragon Magazine Issue 342'),
('Dragon Magazine Issue 343'),
('Dragon Magazine Issue 344'),
('Dragon Magazine Issue 345'),
('Dragon Magazine Issue 346'),
('Dragon Magazine Issue 347'),
('Dragon Magazine Issue 348'),
('Dragon Magazine Issue 349'),
('Dragon Magazine Issue 350'),
('Dragon Magazine Issue 351'),
('Dragon Magazine Issue 352'),
('Dragon Magazine Issue 353'),
('Dragon Magazine Issue 354'),
('Dragon Magazine Issue 355'),
('Dragon Magazine Issue 356'),
('Dragon Magazine Issue 357'),
('Dragon Magazine Issue 358'),
('Dragon Magazine Issue 359');